#!/bin/sh
set -e

if [[ ! -e appendonly.aof ]]; then
	# Copy and decompress database blobs
	cp /private/redis/* .
	unxz appendonly.aof.xz
	unxz dump.rdb.xz
fi


##
# Default redis:alpine entrypoint script starts here
##

# first arg is `-f` or `--some-option`
# or first arg is `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
	set -- redis-server "$@"
fi

# allow the container to be started with `--user`
#if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
#	chown -R redis .
#	exec su-exec redis "$0" "$@"
#fi

exec "$@"

