version: "2"
volumes: 
  nginx-conf: 
    driver: rancher-nfs
    external: true
  website-files: 
    driver: rancher-nfs
    external: true
services: 
  nginx: 
    external_links: 
      - "mysql/pxc:mysql"
    image: "antergos/docker-wordpress:nginx-alpine"
    labels: 
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: "php-fpm,website-storage"
    volumes: 
      - "ssl-certs"
      - "website-files"
      - "nginx-conf"
  php-fpm: 
    environment: 
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_NAME:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_USER:
    external_links: 
      - "mysql/pxc:mysql"
    image: "antergos/docker-wordpress:php7.1-fpm-alpine"
    labels: 
      io.rancher.container.pull_image: always
    ports: 
      - "9000/tcp"
    volumes: 
      - "website-files"
  website-storage: 
    external_links: 
      - "mysql/pxc:mysql"
    image: lots0logs/antergos-website
    labels: 
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: "true"
    volumes: 
      - "website-files:/srv/antergos.com"
      - "nginx-conf:/etc/nginx"

