#!/bin/sh
set -e

[[ -z "${NODE_ENV}" ]] && export NODE_ENV='development'
[[ -z "${DOMAIN}" ]] && export DOMAIN='forum-staging.antergos.com'

SECRET=$(cat /run/secrets/nodebb_secret)

cd /nodebb

# Copy config into place
cp /config/config.json .

# Set Config Vars
sed -i "s|<DOMAIN>|${DOMAIN}|g;
		s|<SECRET>|${SECRET}|g" config.json

# Static Resources
[[ -e build ]] || mkdir build
[[ -e build/public ]] || ln -s /public build/public

# Give redis some time to come up
sleep 10

# Install NodeBB Deps From yarn.lock File
yarn

# Theme
ln -sf /theme /nodebb/node_modules/nodebb-theme-antergos

# Make sure database schema is up-to-date
./nodebb upgrade


# Run NodeBB!
node loader.js --no-silent --no-daemon

exit $?
