#!/bin/sh
set -e

[[ -z "${NODE_ENV}" ]] && export NODE_ENV='development'
[[ -z "${DOMAIN}" ]] && export DOMAIN='forum-staging.antergos.com'

SECRET=$(cat /run/secrets/nodebb_secret)

cd /nodebb

# Copy config into place
cp /config/config.json .

# Set Config Vars
sed -i "s|<DOMAIN>|${DOMAIN}|g;
		s|<SECRET>|${SECRET}|g" config.json

# Give redis some time to come up
sleep 10

# Install Deps
npm install
install-local --save /theme

# Make sure database schema is up-to-date
./nodebb upgrade

# Run NodeBB!
node loader.js --no-silent --no-daemon

exit $?
