#!/bin/sh
set -e

[[ -z "${NODE_ENV}" ]] && export NODE_ENV='development'
[[ -z "${DOMAIN}" ]] && export DOMAIN='forum-staging.antergos.com'

SECRET=$(cat /run/secrets/nodebb_secret)

cd /nodebb

# Copy config into place
cp /config/config.json .

# Set Config Vars
sed -i "s|<DOMAIN>|${DOMAIN}|g;
		s|<SECRET>|${SECRET}|g" config.json

# Static Resources
[[ -e build ]] || mkdir build
[[ -e build/public ]] || ln -s /public build/public

# Give redis some time to come up
sleep 10

# Install NodeBB
yarn

yarn add \
	nodebb-plugin-dbsearch \
	nodebb-plugin-emoji-extended \
	nodebb-plugin-markdown \
	nodebb-plugin-registration-question \
	nodebb-plugin-soundpack-default \
	nodebb-plugin-spam-be-gone \
	nodebb-widget-essentials \
	nodebb-plugin-emailer-mailgun \
	nodebb-plugin-mentions \
	nodebb-plugin-question-and-answer \
	nodebb-plugin-composer-default \
	nodebb-plugin-imgur \
	nodebb-plugin-blog-comments \
	nodebb-plugin-gravatar \
	nodebb-plugin-ns-likes \
	nodebb-plugin-codeinput \
	nodebb-plugin-emoji-apple \
	nodebb-plugin-ns-login \
	nodebb-plugin-poll \
	nodebb-plugin-write-api \
	nodebb-plugin-emoji-static \
	nodebb-plugin-sso-auth0 \
	nodebb-plugin-topic-tags

# Theme
ln -sf /theme /nodebb/node_modules/nodebb-theme-antergos
#cp -r /theme /nodebb-theme-antergos
#cp -r /nodebb-theme-antergos /nodebb/node_modules
#rm -rf /nodebb/node_modules/nodebb-theme-antergos/.git

# Make sure database schema is up-to-date
./nodebb upgrade


# Run NodeBB!
./nodebb start

#while true
#do
#	sleep 10
#done

exit $?
