#!/bin/sh
set -e

# Prepare database files
cd /private/forum
tar -xf redis/appendonly.aof.tar.xz
tar -xf redis/dump.rdb.tar.xz

cd redis


##
# Default redis:alpine entrypoint script starts here
##

# first arg is `-f` or `--some-option`
# or first arg is `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
	set -- redis-server "$@"
fi

# allow the container to be started with `--user`
#if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
#	chown -R redis .
#	exec su-exec redis "$0" "$@"
#fi

exec "$@"

