#!/bin/sh
set -e

cd /run

if [[ ! -e redis ]]; then
	# Prepare database files
	tar -xf secrets/redis_aof
	tar -xf secrets/redis_rdb
fi

cd redis


##
# Default redis:alpine entrypoint script starts here
##

# first arg is `-f` or `--some-option`
# or first arg is `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
	set -- redis-server "$@"
fi

# allow the container to be started with `--user`
#if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
#	chown -R redis .
#	exec su-exec redis "$0" "$@"
#fi

exec "$@"

