version: '3'

services:
  nodebb:
    build:
      context: ./nodebb-alpine
      args:
        - NODE_ENV
    image: antergos/nodebb-alpine
    volumes:
      - private:/private
      - theme:/theme

  nginx:
    image: nginx:alpine
    environment:
      NODE_ENV: "${NODE_ENV}"
    ports:
      - '8080:8080'
    command: ["nginx", "-g", "daemon off;"]
    entrypoint: /entrypoint/nginx
    volumes:
      - private:/private
      - entrypoints:/entrypoint

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    entrypoint: /entrypoint/redis
    volumes:
      - private:/private
      - entrypoints:/entrypoint

volumes:
  private:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/private"
  entrypoints:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/entrypoints"
  theme:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/theme"

