version: '3.1'

services:
  nodebb:
    build:
      context: ./nodebb-alpine
      args:
        NODE_ENV: "${NODE_ENV}"
    image: antergos/nodebb-alpine
    secrets:
      - nodebb_secret
    volumes:
      - config:/config
      - entrypoints:/entrypoint
      - public:/public
      - private:/private
      - theme:/theme

  nginx:
    image: nginx:alpine
    environment:
      NODE_ENV: "${NODE_ENV}"
    ports:
      - '8081:80'
    command: ["nginx", "-g", "daemon off;"]
    entrypoint: /entrypoint/nginx
    depends_on:
      - nodebb
    volumes:
      - config:/config
      - entrypoints:/entrypoint
      - public:/public

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    entrypoint: /entrypoint/redis
    volumes:
      - config:/config
      - entrypoints:/entrypoint
      - private:/private

secrets:
  nodebb_secret:
    file: ./private/nodebb/SECRET

volumes:
  config:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/config"
  entrypoints:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/entrypoints"
  private:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/private"
  public:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/public"
  theme:
    driver: local-persist
    driver_opts:
      mountpoint: "${PWD}/theme"

